const exampleTheme = {
    blockCursor: "editor-blockCursor",
    code: "editor-code",
    placeholder: "editor-placeholder",
    codeHighlight: {
      atrule: "editor-tokenAttr",
      attr: "editor-tokenAttr",
      boolean: "editor-tokenProperty",
      builtin: "editor-tokenSelector",
      cdata: "editor-tokenComment",
      char: "editor-tokenSelector",
      class: "editor-tokenFunction",
      "class-name": "editor-tokenFunction",
      comment: "editor-tokenComment",
      constant: "editor-tokenProperty",
      deleted: "editor-tokenProperty",
      doctype: "editor-tokenComment",
      entity: "editor-tokenOperator",
      function: "editor-tokenFunction",
      important: "editor-tokenVariable",
      inserted: "editor-tokenSelector",
      keyword: "editor-tokenAttr",
      namespace: "editor-tokenVariable",
      number: "editor-tokenProperty",
      operator: "editor-tokenOperator",
      prolog: "editor-tokenComment",
      property: "editor-tokenProperty",
      punctuation: "editor-tokenPunctuation",
      regex: "editor-tokenVariable",
      selector: "editor-tokenSelector",
      string: "editor-tokenSelector",
      symbol: "editor-tokenProperty",
      tag: "editor-tokenProperty",
      url: "editor-tokenOperator",
      variable: "editor-tokenVariable"
    },
    embedBlock: {
      base: 'editor-embedBlock',
      focus: 'editor-embedBlockFocus',
    },
    hashtag: 'editor-hashtag',
    heading: {
      h1: 'editor-heading-h1',
      h2: 'editor-heading-h2',
      h3: 'editor-heading-h3',
      h4: 'editor-heading-h4',
      h5: 'editor-heading-h5',
      h6: 'editor-heading-h6'
    },
    image: 'editor-image',
    indent: 'editor-indent',
    inlineImage: 'editor-inline-image',
    layoutContainer: 'editor-layoutContainer',
    layoutItem: 'editor-layoutItem',
    link: 'editor-link',
    list: {
      listitem: 'editor-listItem',
      listitemChecked: 'editor-listItemChecked',
      listitemUnchecked: 'editor-listItemUnchecked',
      nested: {
        listitem: 'editor-nestedListItem',
      },
      olDepth: [
        'editor-ol1',
        'editor-ol2',
        'editor-ol3',
        'editor-ol4',
        'editor-ol5',
      ],
      ul: 'editor-ul',
    },
    ltr: "ltr",
    rtl: "rtl",
    mark: 'editor-mark',
    markOverlap: 'editor-markOverlap',
    paragraph: 'editor-paragraph',
    quote: "editor-quote",
    table: 'editor-table',
    tableAddColumns: 'editor-tableAddColumns',
    tableAddRows: 'editor-tableAddRows',
    tableCell: 'editor-tableCell',
    tableCellActionButton: 'editor-tableCellActionButton',
    tableCellActionButtonContainer:
      'editor-tableCellActionButtonContainer',
    tableCellEditing: 'editor-tableCellEditing',
    tableCellHeader: 'editor-tableCellHeader',
    tableCellPrimarySelected: 'editor-tableCellPrimarySelected',
    tableCellResizer: 'editor-tableCellResizer',
    tableCellSelected: 'editor-tableCellSelected',
    tableCellSortedIndicator: 'editor-tableCellSortedIndicator',
    tableResizeRuler: 'editor-tableCellResizeRuler',
    tableSelected: 'editor-tableSelected',
    tableSelection: 'editor-tableSelection',
    text: {
      bold: "editor-text-bold",
      italic: "editor-text-italic",
      overflowed: "editor-text-overflowed",
      hashtag: "editor-text-hashtag",
      underline: "editor-text-underline",
      subscript: 'editor-text-subscript',
      superscript: 'editor-text-superscript',
      strikethrough: "editor-text-strikethrough",
      underlineStrikethrough: "editor-text-underlineStrikethrough",
      code: "editor-text-code"
    },
  };
  
  export default exampleTheme;